name: check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: nix flake check
        run: nix flake check --all-systems
